site_name: 100 Go Mistakes and How to Avoid Them
site_url: https://100go.co
repo_name: teivah/100-go-mistakes
theme:
  name: material
  custom_dir: overrides
  favicon: img/Go-Logo_LightBlue.svg
  language: en
  logo: img/Go-Logo_White.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - navigation.expand
    - navigation.instant
    - navigation.sections
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: cyan
      accent: pink
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey
      accent: blue
repo_url: https://github.com/teivah/100-go-mistakes
plugins:
  - search
  - glightbox
  - social:
      cards_layout_options:
        logo: img/cover.png
extra:
  analytics:
    provider: google
    property: G-HMY1HYDM93
  alternate:
    - name: üá¨üáß English
      link: /
      lang: en
    - name: üá®üá≥ Chinese (Simplified)
      link: /zh/
      lang: zh
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/teivah
extra_css:
  - stylesheets/extra.css
nav:
    - Book:
        - book.md
        - chapter-1.md
        - external.md
    - Go Mistakes:
      - index.md
      - Full Sections:
        - 9-generics.md
        - 20-slice.md
        - 28-maps-memory-leaks.md
        - 56-concurrency-faster.md
        - 89-benchmarks.md
        - 98-profiling-execution-tracing.md
    - ‚ù§Ô∏è Go Jobs:
      - jobs.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
copyright: Copyright &copy; 2022 - 2023 Teiva Harsanyi
